### ISSUE TITLE
MAX_NUMBER_OF_COORDINATES 为什么是 20000？

### ISSUE THREAD

**Issue by c9n** [kekee000/fonteditor-ttf#1]
https://github.com/kekee000/fonteditor-ttf/blob/deaa68a3ad8bb291643c73b550dad3a867cd6c80/lib/ttf/table/glyf/parse.js#L13

咨询个问题，MAX_NUMBER_OF_COORDINATES 为什么是 20000？

这个数字是个 `magic number` 么

**Comment by kekee000** [comment]
设置这个阈值是为了防止有些字形读取错误，导致无法跳出循环。20000是我自己拍脑袋拍出来的，真实坐标不会达到20000，如果超过了说明数据有问题，应该跳过读取该字形。

**Comment by c9n** [comment]
前段时间用一个字体，碰到超出的情况了。
没细看是因为什么。
